### ISSUE TITLE
Perceived failure to save profile picture

### ISSUE THREAD

**Issue by doub1ejack** [DemocracyLab/CivicTechExchange#896]
Found a small UX thing when updating my profile pic. It would not work if I clicked Save before I clicked Done Cropping. I tried & failed to update my photo the other day.

For a quick fix, perhaps the save button could be hidden or disabled until the required cropping has happened. Etc. Thanks!

<img src="https://user-images.githubusercontent.com/1809882/183705446-08dc6b0a-bb86-406d-87b9-4f6f94d77070.png" width="300">

**Comment by schaferyan** [comment]
I'd be interested in looking into this one

**Comment by marlonkeating** [comment]
The library we use is [react-image-crop](https://github.com/DominicTobias/react-image-crop), which we wrap with the component:
https://github.com/DemocracyLab/CivicTechExchange/blob/5a0f28ddb62e7dd57ca3baebfcc43f805c807245/common/components/common/upload/ImageCropUploadButton.jsx

**Comment by ddfridley** [comment]
@schaferyan Hi, I'm helping with development focus for DemocarcyLab. We've created a [DemocracyLab Dashboard](https://github.com/orgs/DemocracyLab/projects/1/views/1?layout=board) and would like to update the status of this issue.

There is an unresoved comment in the PR #911 
> Changing project thumbnails fails with the following console error:
ImageCropUploadButton.jsx:123 Uncaught TypeError: this.props._onIsCroppingChanged is not a function at ImageCropUploadButton._handleFileSelection (ImageCropUploadButton.jsx:123:16) at FileReader.<anonymous> (FileSelectButton.jsx:71:18)

Are you still working on this? If so, what are the next steps, or what challenges are there to moving forward?
Or is this still an issue/should we close it?
Or, if you just aren't available to work on it anymore, please let me know, and/or unassign yourself
Or something else?

Thanks.

**Comment by schaferyan** [comment]
Hi David,

Thanks for reaching out! I''m sorry, I haven't had time to work on
Democracy Lab stuff recently.

I can't recall the details of that issue and I unfortunately don't have an
environment set up to check.

Best,
Ryan

**Comment by Nostromos** [comment]
@ddfridley Happy to take this if its still available, which it seems to be.

**Comment by ddfridley** [comment]
@Nostromos please consider that we need to make the QA testing as simple as possible - meaning change the least files and lines of code as possible. Also I am working on adding storybook, an environment for running and testing react components. Maybe we can be a good candidate for that.  Lets talk more about that when I get back from vacation.

**Comment by Nostromos** [comment]
Understood. I think the simplest approach is:

1.  moving state to parent, 
2. passing a setter to child, 
3. requiring a completed crop to save and close parent (the parent button text might be Done)
4. Adding a required field message if someone tries to move on without completing crop ("Click 'Done Cropping' if crop is complete or 'Cancel'" - something along those lines).

Simpler still might be autosaving crop after a short delay and not requiring the "Done Cropping" button to be clicked but I need to look into it more. 

The bigger problem is that I never learned class-based react, flux, or flow (lol) so I'm still figuring out how to get my IDE not to throw errors on *everything*. I'll figure it out.

**Comment by Nostromos** [comment]
@marlonkeating @ddfridley Hey I think I've got it figured out. Can I get perms to push my branch up so I can draft a PR? There's still some testing left to do.
